### ISSUE TITLE
Multilib missing

### ISSUE THREAD

**Issue by jruere** [VictorBjelkholm/arch-mirror#4]
If multilib is not supported, it could be mentioned in the REAME as well as including a configuration that would work.

What I did is change `pacman.conf` to include your IPFS mirror only for the supported parts. For example:

    [core]
    Server = http://localhost:8082/ipns/arch.victor.earth/$repo/os/$arch
    Include = /etc/pacman.d/mirrorlist

**Comment by jruere** [comment]
Will this be a problem if other mirror updates more often and I use it only for multilib?

**Comment by VictorBjelkholm** [comment]
Are you sure it's not already supported? I can see http://arch.victor.earth/multilib/os/x86_64 so if it's not working for you, could you share what errors you are getting?

**Comment by jruere** [comment]
You are 100% correct. I don't know what I saw... apologies.
